version: '3.3'

services:
  # actually using outsourced db rn
  # mongodb:
  api:
    image: ghcr.io/pastebin-fi/powerpaste:master
    restart: always
    container_name: pastebin_api
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
    ports:
      - '6789:3001'
    env_file:
      - .env

  watchtower:
    image: containrrr/watchtower
    restart: always
    container_name: pastebin_watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    command: --interval 10 pastebin_api
